HomeWork_22_2_WebClient/Controllers/PhoneBookController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace HomeWork_22_2_WebClient.Controllers
{
    public class PhoneBookController : Controller
    {
        private IPhoneBook phoneBook;
        private IAppUser appUser;
        public PhoneBookController(IPhoneBook phoneBook, IAppUser appUser)
        {
            this.phoneBook = phoneBook;
            this.appUser = appUser;
        }

        public IActionResult Index()
        {
            var ph = phoneBook.GetPhoneBook();
            ViewData["logIn"] = appUser.logIn;
            ViewData["UserName"] = appUser.UserName;
            return View(ph);
        }
        public RedirectToActionResult AddRecord()
        {
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<RedirectToActionResult> AddRecord(string LastName, string FirstName, string ThreeName, string NumberPhone,
            string Address, string Description)
        {
            PhoneBook phoneBookL = new PhoneBook();
            phoneBookL.FirstName = FirstName;
            phoneBookL.LastName = LastName;
            phoneBookL.ThreeName = ThreeName;
            phoneBookL.NumberPhone = NumberPhone;
            phoneBookL.Address = Address;
            phoneBookL.Description = Description;
            await phoneBook.AddRecord(phoneBookL, appUser);
            return RedirectToAction("Index");
        }

        public RedirectToActionResult DeleteRecord()
        {
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<RedirectToActionResult> DeleteRecord(int id)
        {
            await phoneBook.DeleteRecord(id, appUser);
            return RedirectToAction("Index");
        }

        public RedirectToActionResult EditRecord()
        {
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<RedirectToActionResult> EditRecord(int id, string LastName, string FirstName, string ThreeName, string NumberPhone,
            string Address, string Description)
        {
            PhoneBook phoneBookL = new PhoneBook();
            phoneBookL.PhoneBookID = id;
            phoneBookL.FirstName = FirstName;
            phoneBookL.LastName = LastName;
            phoneBookL.ThreeName = ThreeName;
            phoneBookL.NumberPhone = NumberPhone;
            phoneBookL.Address = Address;
            phoneBookL.Description = Description;
            await phoneBook.EditRecord(phoneBookL, appUser);
            return RedirectToAction("Index");
        }
    }
}

HomeWork_22_2_WebClient/Controllers/RecordController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HomeWork_22_2_WebClient.Models;

namespace HomeWork_22_2_WebClient.Controllers
{
    public class RecordController : Controller
    {
        private IPhoneBook repository;
        private IAppUser appUser;

        public RecordController(IPhoneBook repo, IAppUser appUser)
        {
            repository = repo;
            this.appUser = appUser;
        }
        public ViewResult Index(PhoneBook phoneBook)
        {
            ViewData["logIn"] = appUser.logIn;
            ViewData["UserName"] = appUser.UserName;
            return View(phoneBook);
        }

        public RedirectToActionResult ViewRecord(int id)
        {
            var phoneBook = repository.GetPhoneBookId(id);
            ViewData["logIn"] = appUser.logIn;
            ViewData["UserName"] = appUser.UserName;
            return RedirectToAction("Index", phoneBook);
        }

        public ViewResult ViewAddRecord()
        {
            ViewData["logIn"] = appUser.logIn;
            ViewData["UserName"] = appUser.UserName;
            return View();
        }
        public ViewResult ViewEditRecord(int id, string LastName, string FirstName, string ThreeName, string NumberPhone, string Address, string Description)
        {
            ViewData["logIn"] = appUser.logIn;
            ViewData["UserName"] = appUser.UserName;
            PhoneBook phoneBookL = new PhoneBook();
            phoneBookL.PhoneBookID = id;
            phoneBookL.FirstName = FirstName;
            phoneBookL.LastName = LastName;
            phoneBookL.ThreeName = ThreeName;
            phoneBookL.NumberPhone = NumberPhone;
            phoneBookL.Address = Address;
            phoneBookL.Description = Description;
            return View(phoneBookL);
        }
    }
}

HomeWork_22_2_WebClient/Views/PhoneBook/Index.cshtml
@{
    ViewData["Title"] = "Записная книжка";
}
@model IEnumerable<PhoneBook>

<div class="row m-1 p-1">
    <div class="col-2">
            <form asp-action="ViewAddRecord" asp-controller="Record" method="post">
                <button type="submit" class="btn btn-block btn-primary">
                    Добавить запись
                </button>
            </form>
    </div>
    <div class="col-10">
        @foreach (var p in Model)
        {
            <div class="card card-outline-primary m-1 p-1">
                <div>
                    <form id="@p.PhoneBookID" asp-action="ViewRecord"
                          asp-controller="Record" method="post" class="d-inline-flex">
                        <input type="hidden" name="id"
                               value="@p.PhoneBookID" />
                        <button type="submit"
                                class="btn btn-secondary btn-sm">
                            @p.PhoneBookID
                        </button>
                    </form>
                    <div class="d-inline-flex">
                        @p.LastName @p.FirstName @p.ThreeName
                    </div>
                    <form id="@p.PhoneBookID" asp-action="DeleteRecord"
                          asp-controller="PhoneBook" method="post" class="d-inline-flex pull-right" style="float:right">
                        <input type="hidden" name="id"
                               value="@p.PhoneBookID" />
                        <button type="submit"
                                class="btn btn-danger btn-sm">
                            Удалить
                        </button>
                    </form>
                    <form id="@p.PhoneBookID" asp-action="ViewEditRecord"
                          asp-controller="Record" method="post" class="d-inline-flex pull-right" style="float:right">
                        <input type="hidden" name="id" value="@p.PhoneBookID"/>
                        <input type="hidden" name="LastName" value="@p.LastName"/>
                        <input type="hidden" name="FirstName" value="@p.FirstName"/>
                        <input type="hidden" name="ThreeName" value="@p.ThreeName"/>
                        <input type="hidden" name="NumberPhone" value="@p.NumberPhone"/>
                        <input type="hidden" name="Address" value="@p.Address"/>
                        <input type="hidden" name="Description" value="@p.Description"/>
                        <button type="submit" class="btn btn-success btn-sm">
                            Редактировать
                        </button>
                    </form>
                </div>
            </div>
        }
    </div>
</div>